services:
    nginx:
        build: requirements/nginx/.
        container_name: nginx
        env_file:
            - ./.env
        environment:
            - DOMAIN_NAME=${DOMAIN_NAME}
        ports:
            - "443:443"
        depends_on:
            - wordpress
        networks:
            - inception
        volumes:
            - ./requirements/volumes/wordpress:/var/www/html  # Share WordPress files with Nginx

    wordpress:
        build: requirements/wordpress/.
        container_name: wordpress
        env_file:
            - ./.env
        depends_on:
            - mariadb
        # No direct port exposure needed for WordPress with PHP-FPM
        environment:
            - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
            - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
            - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
            - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
            - DOMAIN_NAME=${DOMAIN_NAME}
        volumes:
            - ./requirements/volumes/wordpress:/var/www/html
        networks:
            - inception

    mariadb:
        build: requirements/mariadb/.
        container_name: mariadb
        env_file:
            - ./.env
        environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
        - ./requirements/volumes/mariadb:/var/lib/mysql
        networks:
        - inception

networks:
    inception:
        driver: bridge