FROM mariadb:latest

# Copy custom configuration
#COPY my.cnf /etc/mysql/my.cnf

# Run additional setup scripts
#COPY init.sql /docker-entrypoint-initdb.d/

# Expose a specific port if needed (default is 3306)
EXPOSE 3306
